import Head from "next/head";
import styles from "../styles/Home.module.css";
import { useState, Fragment} from "react";
import Image from "next/image";
import { cardArray } from "../components/cardArray";

import { Main } from "../components/main/style";
import { TwoDimentionGrid, Card } from "../components/twoDimensionGrid/style";
import { Switch, Handle } from "../components/toggle/style";

export default function Home() {
  const [isOn, setIsOn] = useState(true);
  const toggleSwitch = () => setIsOn(!isOn);

  const spring = {
    type: "spring",
    stiffness: 700,
    damping: 30,
  };

  const randomizer = () => {
    const options = ["flex-end", "flex-start"];
    const randomNumber = Math.floor(Math.random() * 2);
    return options[randomNumber];
  };

  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Main>
        {/* <Switch toggle={isOn} onClick={toggleSwitch}>
            <Handle layout transition={spring}></Handle>
          </Switch> */}
        <TwoDimentionGrid>
          {cardArray.map((item, index) => (
            <Fragment key={`fragment${index}`}>
              <Card
                style={
                  item.imgAlt.includes("dummy")
                    ? { justifyContent: randomizer(), alignItems: randomizer() }
                    : { justifyContent: "center", alignItems: "center" }
                }
                
              >
                <Image
                  
                  style={
                    item.imgAlt.includes("dummy")
                      ? { height: "auto", maxWidth: "50%", }
                      : { height: "auto", width: "100%" }
                  }
                  alt={`${item.imgAlt} ${index + 1}`}
                  src={item.imgScr}
                />
                <p >{index + 1}</p>
              </Card>
            </Fragment>
          ))}
        </TwoDimentionGrid>
      </Main>
    </div>
  );
}
